// Réservation express de l'accueil : choix → « Confirmer » → tunnel ouvert à l'étape coordonnées → succès
import { chromium } from "playwright";
import { existsSync } from "node:fs";
const chrome = () => process.env.CHROME_PATH || (existsSync("/opt/pw-browsers/chromium-1194/chrome-linux/chrome") ? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" : undefined);
const base = process.argv[2] ?? "http://localhost:3100";
const out = process.argv[3];
const b = await chromium.launch({ executablePath: chrome() });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
await ctx.addInitScript(() => localStorage.setItem("dg-consent", '{"mesure":false}'));
const p = await ctx.newPage();
const erreurs = [];
p.on("pageerror", (e) => erreurs.push(e.message));
await p.goto(base + "/", { waitUntil: "networkidle" });
const bloc = p.locator("#reserver-express");
await bloc.scrollIntoViewIfNeeded();
await bloc.getByText("Coupe + barbe", { exact: true }).click();
await bloc.getByText("Théo", { exact: true }).click();
const jours = bloc.locator("button[aria-pressed]:not([disabled])").filter({ hasText: /^\d+$/ });
console.log("jours réservables affichés :", await jours.count());
if ((await jours.count()) > 1) await jours.nth(1).click();
const heures = bloc.getByRole("group", { name: "Horaires libres" }).locator("button");
console.log("horaires :", await heures.count());
await heures.nth(Math.min(1, (await heures.count()) - 1)).click();
console.log("récap :", (await bloc.locator("dl").innerText()).replace(/\s+/g, " "));
if (out) await bloc.screenshot({ path: out });
await bloc.getByRole("link", { name: "Confirmer le créneau" }).click();
await p.waitForURL(/\/reserver/);
await p.waitForSelector("#prenom", { timeout: 8000 });
console.log("URL :", p.url().replace(base, ""));
await p.fill("#prenom", "Yanis");
await p.fill("#telephone", "06 12 34 56 78");
await p.check('input[name="consentement"]');
await p.getByRole("button", { name: /Confirmer le rendez-vous/ }).click();
await p.waitForSelector("text=C'est noté", { timeout: 8000 });
console.log("succès :", (await p.locator("main").innerText()).match(/C'est noté[^\n]*/)?.[0]);
console.log(erreurs.length ? erreurs : "aucune erreur");
await b.close();
